version: '3.9'


services:

  encoder:
    image: mutagen-video-encoder
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - RABBITMQ__PREFETCH_COUNT=${RABBITMQ__PREFETCH_COUNT}
    restart: unless-stopped
    env_file: .env
    deploy:
      mode: replicated
      replicas: $REPLICAS
    volumes:
      - ./data:/


  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9091"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
