version: '3.9'


services:

  encoder:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - RABBITMQ__PREFETCH_COUNT=2
    restart: unless-stopped
    env_file: ${PWD}/.env
    deploy:
      mode: replicated
      replicas: 1

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9091"
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
