version: "3.9"

services:
  video_encoder:
    image: mutagen-video-encoder
    env_file: .env
    deploy:
      mode: replicated
      replicas: $REPLICAS

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 100
        window: 120s